### ISSUE TITLE
401 On twitter.media.mediaUpload()

### ISSUE THREAD

**Issue by vasanthdeveloper** [FeedHive/twitter-api-client#55]
**Describe the bug**  
Below are the authentication requirements by Twitter for **`twitter.tweets.statusesUpdate()`** and **`twitter.media.mediaUpload()`** endpoints respectively 👇

![Screenshot 2021-02-04 at 8 01 57 PM](https://user-images.githubusercontent.com/24322511/106907223-0842a100-6724-11eb-9748-a454722f198a.png)

and 

![Screenshot 2021-02-04 at 8 01 14 PM](https://user-images.githubusercontent.com/24322511/106907270-142e6300-6724-11eb-8f75-70663106886e.png)

As they require same level of authentication if **`twitter.tweets.statusesUpdate()`** works then **`twitter.media.mediaUpload()`** should also work. Where **`twitter.tweets.statusesUpdate()`** works as expected, **`twitter.media.mediaUpload()`** responds with a `401`. Here's the code I've used 👇

```javascript
const res = await twitter.media.mediaUpload({
    media: await fs.readFile(image.path)
})

console.log('res ', res)
```

And here's the response I get 👇

```javascript
{
    statusCode: 401,
    data: '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'
}
```

**To reproduce**  
1. Create a new Node.js project and add `twitter-api-client` as dependency.
2. Write the following code 👇 in a file named `index.js`
```javascript
const fs = require('fs/promises')

const res = await twitter.media.mediaUpload({
    media: await fs.readFile('./image.png')
})

console.log('res ', res)
```
3. Add a dummy image in the same folder as `index.js`
4. Run it!

**Expected behavior**  
I see the newly uploaded image in Twitter Media Studio.

**Package Manager:**  
To install the Twitter API Client, I used **Yarn v1.22.10**

**Additional context**  
**Node.js:** v15.4.0
**Module System:** Native ESM
**Operating System:** macOS Big Sur 11.1 (20C69)

**Comment by SimonHoiberg** [comment]
Hi @vasanthdeveloper :wave: 
Thanks for creating this issue.

The `mediaUpload` endpoint expects the `media` to be `base64` encoded.
So - without having tried your reproduction example yet - could you first try to do the following:

```
const fs = require('fs/promises')

const res = await twitter.media.mediaUpload({
    media: await fs.readFile('./image.png', { encoding: 'base64' }) // <- add base64 here
})

console.log('res ', res)
```

I have a feeling that will work.
Thank you.

**Comment by vasanthdeveloper** [comment]
@SimonHoiberg Yup! that works 🥳  you're a genius! 🙌

**Comment by vasanthdeveloper** [comment]
@SimonHoiberg It would be great if you make an example of chunked upload since that's tricky 🙂

**Comment by slorber** [comment]
Couldn't make chunked upload work due to auth failures => https://github.com/FeedHive/twitter-api-client/issues/63
