### ISSUE TITLE
Getting the reply count with statusesUserTimeline

### ISSUE THREAD

**Issue by aviNrich** [FeedHive/twitter-api-client#62]
Hi,
Is it possible somehow today to get the reply count when using the method: `await this.twitterClient.tweets.statusesUserTimeline();`

I know in the Twitter UI it apears in `.reply_count`.
Or maybe another request to get this item.

Thanks

**Comment by SimonHoiberg** [comment]
Hi, @aviNrich 

At this moment, it's not directly possible.
But there are a few workarounds.

Check out [this discussion](https://stackoverflow.com/questions/46823700/in-the-twitter-rest-api-is-it-possible-to-find-the-reply-count) on StackOverflow.

**Comment by aviNrich** [comment]
@SimonHoiberg  thank you. 
Correct me if I'm wrong metrics API is not supported in this lib correct?
if not, can I execute "free" authenticated requests to Twitter API? something like:
`twitterApCclient.http.get('/metrics/blabla')` this way I wont have to authenticate twice.

Thanks

**Comment by SimonHoiberg** [comment]
Not at the moment, no.
But that's actually a nice suggestion for a feature :+1: 
We'll look into supporting that!
